templates/deployment-web.yaml, values.yaml
_Port of [#21053](https://github.com/mastodon/mastodon/pull/21053) from [mastodon/mastodon](https://github.com/mastodon/mastodon) repository._
---
The `mastodon.web.minThreads` value won't work until [#21048](https://github.com/mastodon/mastodon/pull/21048) is merged.
=> feat(helm-chart): add values for various Puma related settings

templates/configmap-env.yaml
Fix the following break when a caching proxy is specified:
```
Error: INSTALLATION FAILED: template: mastodon/templates/deployment-web.yaml:21:12: executing "mastodon/templates/deployment-web.yaml" at <include "mastodon.rollingPodAnnotations" .>: error calling include: template: mastodon/templates/_helpers.tpl:60:30: executing "mastodon.rollingPodAnnotations" at <include (print $.Template.BasePath "/configmap-env.yaml") .>: error calling include: template: mastodon/templates/configmap-env.yaml:54:27: executing "mastodon/templates/configmap-env.yaml" at <.Values.mastodon.s3.alias_host>: can't evaluate field Values in type string
```
=> Fix alias_host break on bad var reference (#34)

templates/_helpers.tpl, templates/configmap-env.yaml, templates/deployment-sidekiq.yaml, templates/secret-smtp.yaml, values.yaml
Porting https://github.com/mastodon/mastodon/pull/19919 to the new repo.
---
Sensitive data such as login credentials should not be rendered in a `ConfigMap`, as cluster operators are often more lenient granting applications read permissions for them.
This PR moves `SMTP_LOGIN` and `SMTP_PASSWORD` env vars to a new secret `secret-smtp.yaml`, unless `.Values.mastodon.smtp.existingSecret` is defined. In this case, no secret is created and sidekiq will source the `login` and `password` variables from `.Values.mastodon.smtp.existingSecret`.
This change is backwards-compatible.
=> store smtp credentials on a secret

templates/configmap-env.yaml, values.yaml
Being able to control it can be useful in situations where prepared statements don't work as expected. Once such case can be pgbouncer as provided by DigitalOcean for connection pooling.
=> Add the PREPARED_STATEMENTS environment variable and set it to its default value

values.yaml
The Docker Hub `tootsuite/mastodon` image is deprecated and will soon no longer be available, due to Docker deleting every organisation on a free plan.
Images with the latest tags for all supported releases (3.5, 4.0, 4.1) have been synced here, and new versions will be published on this repo.
=> Update image repository to GHCR

templates/_statsd.yaml, templates/configmap-env.yaml, templates/deployment-sidekiq.yaml, templates/deployment-web.yaml, templates/statsd-exporter-mappings.yaml, values.yaml
Starting with a few distinct changes to clear up the larger diff log between the two repos. I want to coordinate some changes with the existing PRs the community has submitted and tie those in as well.
=> Add sidecar capability for statsd

templates/pvc-assets.yaml
I found a small misreference in the template.
=> fix accessModes misreference in pcv-assets

values.yaml
Since the configmap-env sets the `REDIS_HOST` to `namespace-redis-master` if the `redis.host`value is not set (indicating that an existing Redis install is to be used) any replicas will not be used and the Bitnami chart defaults to 3 unused replicas.
=> Set default Redis replica count to 0

templates/configmap-env.yaml, values.yaml
Did a quick rearrange of a PR I just merged (add `ES_PRESET` as an option in `values.yaml` as the original merge with an outdated branch was a little clunky and resulted in some duplicated lines + not ideal placement.
=> Quick rearrange for ES_PRESET, add to values file

templates/deployment-sidekiq.yaml
Use an unique annotation key for the smtp secret checksum, fixing the conflict mentioned in #48.
=> Use unique annotation key for smtp secret checksum (#48)

values.yaml
This fixes a typo in a comment in `values.yaml`:
"detauls" -> "details"
=> Fix a typo in values.yaml

templates/deployment-sidekiq.yaml, templates/deployment-streaming.yaml, templates/deployment-web.yaml, values.yaml
Allow setting the spec.revisionHistoryLimit value on Deployment resources to a custom value.
=> feat(deployments): make spec.revisionHistoryLimit configurable

Chart.yaml, values.yaml
It seems #126 missed the upgrade to the image tag, and bumping the chart version. Easily done though as it was recently in #122 that I suggested we go with exact version in the tags.
=> chore(deps): upgrade image tag to v4.2.7 and bump chart version

.github/workflows/test-chart.yml, Chart.lock, Chart.yaml, README.md
supersedes https://github.com/mastodon/chart/pull/91
- redis chart [updated from 16.x to 18.x](https://github.com/bitnami/charts/tree/main/bitnami/redis#to-1800), which upgrades the default version of redis used from 6 to 7
- [redis 7.0 changelog](https://raw.githubusercontent.com/redis/redis/7.0/00-RELEASENOTES)
- [redis 7.2 changelog](https://raw.githubusercontent.com/redis/redis/7.2/00-RELEASENOTES)
- postgresql chart [updated from 11.x to 14.x](https://github.com/bitnami/charts/tree/main/bitnami/postgresql#to-1400)
- updates the default version of postgresql from 14 to 16 - [upgrade notes for 14 to 15](https://www.postgresql.org/docs/15/upgrading.html) - [upgrade notes for 15 to 16](https://www.postgresql.org/docs/16/upgrading.html)
- changes how `NetworkPolicy` objects are created
=> deps: update to latest versions, switch to OCI repo [semver-major]

templates/deployment-streaming.yaml, values.yaml
This PR addresses #86 
Node.js appears to be more picky about self-signed certificates than rails. That said, it accepts a (singular) file containing one or more root certificates that should be trusted alongside the system's CAs. This changeset declares a short stanza, `mastodon.streaming.extraCerts`, empty by default, which can pull a .crt file from an existing secret. It then mounts that file as a projected volume and passes the filepath to node via an env var. The stanza also allows users to set the TLS "mode" (read: validation strictness) that Node will use. In my testing, it seemed that `no-verify` may be necessary for some root certs, but can be avoided often enough that it seems wise not to use it as a default value.
Lastly, the stanza allows you to pick a custom name for the …
=> Add values to inject trusted certs into streaming

README.md
The current instructions instruct to always update dependencies to the latest in range instead of installing the currently locked version. This ensures you're using the tested locked versions.
=> Helm dep should use install

templates/_helpers.tpl, templates/secret-smtp.yaml
Replace common.names.fullname in the default Secret name template with mastodon.fullname
This removes all Bitnami dependencies for installs not using the Bitnami PostgreSQL, Redis, and Elasticsearch. Those charts populate the common.names.fullname template value. Installs not using these charts will receive an error. Instead, use mastodon.fullname like in secrets.yaml.
Fix mastodon/chart#60
Fix mastodon/chart#65
=> Change default Secret name to not rely on Bitnami

templates/configmap-env.yaml, values.yaml
When uploading data to S3, if the number of bytes to send exceedes multipart_threshold then a multi part session is automatically started and the data is sent up in chunks.
=> Add s3.mastodon.multipart_threshold config option

templates/deployment-sidekiq.yaml
If you're using an internal SMTP server which doesn't use authentication for services, then the helm chart deploys an unusable sidekiq container;
```console
$ kubectl --namespace mastodon get pods
...
mastodon-sidekiq-all-queues-58c6b4948f-fktj6   0/1     CreateContainerConfigError   0                24s
$ kubectl --namespace get events | grep sidekiq
...
32s       Warning   Failed                   pod/mastodon-sidekiq-all-queues-58c6b4948f-fktj6    Error: couldn't find key password in Secret mastodon/mastodon-smtp
```
=> Fix container create error on unauthenticated SMTP

templates/deployment-sidekiq.yaml
`values.yaml` says:
```
sidekiq:
podSecurityContext: {}
securityContext: {}
```
However, this was not true before this PR: Only `sidekiq.securityContext` was considered, defaulting to an empty security context if it was not set.
=> fix inheritance of sidekiq securityContext

Chart.yaml, templates/deployment-sidekiq.yaml, templates/deployment-streaming.yaml, templates/deployment-web.yaml
Web pods, especially ones with many DB connections, can sometimes take more time to come back up, and have the highest user impact if they are all get replaced too quickly. This slows down how quickly web pods are swapped out, and adds a small delay in their readiness probe to allow them to get situated.
=> Rollout tuning

Chart.yaml, templates/deployment-streaming.yaml
Endpoint type for the startup probe for the streaming pods was the incorrect type. Now fixed.
=> Fix endpoint type for healthcheck for streaming pods

templates/configmap-env.yaml, values.yaml
Mastodon [v4.2.9](https://github.com/mastodon/mastodon/releases/tag/v4.2.9) started performing stricter checks to prevent client IP address spoofing. This environmental variable is required for use behind reverse proxy servers.
=> Add TRUSTED_PROXY_IP option

Chart.yaml, templates/deployment-sidekiq.yaml, templates/deployment-streaming.yaml, templates/deployment-web.yaml, values.yaml
There have been several situations where I've needed to assign labels/annotations to either deployment objects themselves, and/or the resulting pods. There are already some mechanisms for this in the chart, but they are not documented in `values.yaml`, or override other global fields.
This adds additional fields to each of the components to allow for custom, deployment- or pod-specific labels and annotations that are applied in addition to any global annotations and labels.
=> Better control of labels/annotations for deployments and pods

templates/configmap-env.yaml
When using mail addresses (`from_address`, `return_path` or `reply_to`) that includes the sender name e.g. `some fancy name <mastodon@domain.tld>` the `<>` need to be escaped or helm otherwise fails with the following error:
`Error: YAML parse error on mastodon/templates/configmap-env.yaml: error converting YAML to JSON: yaml: line 40: found character that cannot start any token`
=> quote smtp from, return and reply addresses

templates/configmap-env.yaml
Latest version will not deploy to kubernetes without it being quoted. See the following:
```
$ helm upgrade --install -n mastodon mastodon chart/ -f values.yaml
Error: UPGRADE FAILED: failed to create resource: ConfigMap in version "v1" cannot be handled as a ConfigMap: json: cannot unmarshal number into Go struct field ConfigMap.data of type string
```
With these values:
```
postgresql:
enabled: false
postgresqlHostname: mastodon-db
kubepostgresqlPort: "5432"
auth:
database: mastodon
username: mastodon
existingSecret: "mastodon.mastodon-db.credentials.postgresql.acid.zalan.do"
readReplica:
hostname: mastodon-db-repl
port: "5432"
auth:
database: mastodon
username: mastodon
existingSecret: "mastodon.mastodon-db.credentials.postgresql.acid.zalan.do"
```
It being quoted (or not) in values …
=> Make sure to quote replica db port value

templates/_db-migrate.tpl, templates/_helpers.tpl, values.yaml
When using a connection pooler like pgbouncer, migrations will fail when being done through the pooler. The solution is to provide a "direct" connection to the migration pods so they don't run into this issue.
Fixes #168
=> Added additional DB connection fields to deal with connection pooler migrations

templates/job-db-prepare.yaml, templates/secret-prepare.yml
Discovered a really silly bug with how templates + comments work. This fixes it.
=> Fix some helm typos (comments interfering with manifests)

templates/service-streaming.yaml, templates/service-web.yaml
At the moment, the Helm chart does not allow clean installation on Kubernetes clusters running in dual-stack mode.
For example, on my own k3s cluster, the Mastodon services are assigned only IPv6 addresses and use only IPv6 endpoints, which fails both IPv4 clients and causes problems with the Mastodon pods which, at the moment, only bind to IPv4 addresses on a dual-stack cluster. (The related issue to fix that problem is here: https://github.com/mastodon/mastodon/issues/25371 ; at the moment I had to bypass it by hacking BIND definitions into this Helm chart, but a proper fix would obviously be preferable.)
This PR remedies the problem by setting _ipFamilyPolicy: PreferDualStack_ on the services the chart creates, which makes dual-stack clusters operate correctly and should have no …
=> Allow dual-stack operation on clusters so equipped.

CHANGELOG.md
This is a preparatory PR for when several PRs have successfully been merged in. Just updating the changelog. This is especially important as there are some PRs that contain breaking changes (but are easily addressable), so these need to be documented.
This will only be merged once all the other PRs have been merged.
=> Update changelog for chart v6 (app 4.3)

CHANGELOG.md, Chart.yaml, templates/_db-migrate.tpl, templates/job-db-prepare.yaml, values.yaml
For situations where someone is using something like Argo CD (which doesn't differentiate between `pre-install` and `pre-upgrade` jobs can be run at the same time. Which is fine ultimately, but can sometimes result in colliding jobs. This should fix that.
=> Fix ordering for db:prepare and db:migrate

CHANGELOG.md, Chart.yaml, templates/job-deploy-search.yaml, values.yaml
This creates a simple job template to fire off when deploying elasticsearch, e.g. as part of upgrading to 4.2.0 and beyond.
=> Add job template to deploy search

CHANGELOG.md, Chart.yaml, templates/_helpers.tpl
Shortens any digest information from the image tag when filling out `app.kubernetes.io/version`, to only 7 characters of the hash, as this often runs over the 63 character limit.
For example:
`image:tag@sha256:a86ee592e88df1b85951a1d895f487c3549beb3f57da4ceb7d8ca9d6992d5da9`
becomes
`image:tag@sha256:a86ee59`
=> Don't include entire digest versions in app version label

CHANGELOG.md, Chart.yaml, templates/_helpers.tpl, templates/configmap-env.yaml
Response to the discussion in PR #160. Removes `DB_POOL` override.
=> Remove DB_POOL from configuration
